{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "loyalty-platform-v1.fullname" . }}-kafka-pvc
  labels:
    app: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.persistence.size }}
  storageClassName: standard
{{- end }}
