apiVersion: v1
kind: Service
metadata:
  name: {{ include "loyalty-platform-v1.fullname" . }}-keycloak
  labels:
    app: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - port: {{ .Values.keycloak.service.port }}
      targetPort: {{ .Values.keycloak.service.port }}
      protocol: TCP
      name: http
  selector:
    app: keycloak
