apiVersion: v1
kind: Service
metadata:
  name: {{ include "loyalty-platform-v1.springboot-postgresql.fullname" . }}
  labels:
    app: {{ include "loyalty-platform-v1.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  selector:
    app: {{ include "loyalty-platform-v1.name" . }}
  type: ClusterIP
